### ISSUE TITLE
substr() expects parameter 1 to be string, bool given in MbString.php:340

### ISSUE THREAD

**Issue by joshua-bn** [jfcherng/php-mb-string#1]
```
Fatal error: Uncaught TypeError: substr() expects parameter 1 to be string, bool given in /srv/src/vendor/jfcherng/php-mb-string/src/MbString.php:340
Stack trace:
#0 /srv/src/vendor/jfcherng/php-mb-string/src/MbString.php(340): substr(false, 4)
#1 /srv/src/vendor/jfcherng/php-mb-string/src/MbString.php(71): Jfcherng\Utility\MbString->inputConv('\t\t\tvar re = '',...')
#2 /srv/src/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(153): Jfcherng\Utility\MbString->set('\t\t\tvar re = '',...')
#3 /srv/src/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(89): Jfcherng\Diff\Renderer\Html\AbstractHtml->renderChangedExtent(Object(Jfcherng\Diff\Renderer\Html\LineRenderer\Char), '\t\t\tvar re = '',...', '\t\t\tvar re = '',...')
#4 /srv/src/vendor/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php(113): Jfcherng\Diff\Renderer\Html\AbstractHtml->getChanges(Object(Jfcherng\Diff\Differ))
#5 /srv/src/vendor/jfcherng/php-diff/src/Renderer/AbstractRenderer.php(172): Jfcherng\Diff\Renderer\Html\AbstractHtml->renderWo in /srv/src/vendor/jfcherng/php-mb-string/src/MbString.php on line 340
```

iconv() can return a string or false.

I am guessing this string is what is breaking it but that's a different issue ```'\\s!"#$%&()*+,-./:;<=>?@[\]^_{|}����������������\u201d\u201c'```

**Comment by joshua-bn** [comment]
Both of these are not type safe:
```
    // convert the output string to its original encoding
    protected function outputConv(string $str): string
    {
        if ($str === '') {
            return '';
        }

        return \iconv('UTF-32', $this->encoding, static::$utf32Header . $str);
    }

    // convert the input string to UTF-32 without header
    protected function inputConv(string $str): string
    {
        if ($str === '') {
            return '';
        }

        // we don't want the header so first 4 bytes are stripped
        return \substr(\iconv($this->encoding, 'UTF-32', $str), 4);
    }
```

**Comment by jfcherng** [comment]
Can you provide a reproducer? If it involves special Unicode characters, attachments may be preferred. `iconv()` should not return `false` unless there is an illegal char. My best guess at this moment is that your input is not UTF-8.

`� REPLACEMENT CHARACTER used to replace an unknown, unrecognized or unrepresentable character` happens when you have an illegal char such as open ISO-8859-1 encoded string as UTF-8.

**Comment by jfcherng** [comment]
closed due to inactivity.
